/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "AMux_1.h"
#include "ADC_DelSig_1.h"
#include "A0_Pin_aliases.h"
#include "A0_Pin.h"
#include "A1_Pin_aliases.h"
#include "A1_Pin.h"
#include "A2_Pin_aliases.h"
#include "A2_Pin.h"
#include "D4_Pin_11_aliases.h"
#include "D4_Pin_11.h"
#include "D5_Pin_12_aliases.h"
#include "D5_Pin_12.h"
#include "D6_Pin_13_aliases.h"
#include "D6_Pin_13.h"
#include "D7_Pin_14_aliases.h"
#include "D7_Pin_14.h"
#include "Enable_Pin_6_aliases.h"
#include "Enable_Pin_6.h"
#include "R_W_Pin_5_aliases.h"
#include "R_W_Pin_5.h"
#include "RS_Pin_4_aliases.h"
#include "RS_Pin_4.h"
#include "LCD_Char_1.h"
#include "ADC_DelSig_1_Ext_CP_Clk.h"
#include "ADC_DelSig_1_IRQ.h"
#include "ADC_DelSig_1_theACLK.h"
#include "LCD_Char_1_LCDPort_aliases.h"
#include "LCD_Char_1_LCDPort.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

